name: Deploy API to AWS EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: "us-east-1"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out code
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Build Docker Image
    - name: Build Docker image
      run: |
        docker build -t adrylr/p7_scoring_app:latest .

    # Step 3: Run API in Docker Container and Test
    - name: Run API in Docker container and execute tests
      run: |
        # Start the Docker container
        docker run -d -p 8000:8000 --name test_api_container adrylr/p7_scoring_app:latest

        # Wait for the API to be ready
        sleep 5

        # Run tests against the running API
        docker exec test_api_container pytest /app/tests/test_api.py

        # Stop and remove the container
        docker stop test_api_container && docker rm test_api_container

    # Step 4: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 5: Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker tag adrylr/p7_scoring_app:latest adrylr/p7_scoring_app:latest
        docker push adrylr/p7_scoring_app:latest

    # Step 6: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: ${{ secrets.AWS_ARN }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.AWS_REGION }}

    # Step 7: Deploy to EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          # Install Docker and start the service
          sudo yum update -y
          sudo yum install -y docker
          sudo usermod -aG docker ec2-user
          sudo service docker start

          # Pull and start the container
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull adrylr/p7_scoring_app:latest
          docker run -d -p 80:8000 adrylr/p7_scoring_app:latest
