name: Deploy API to AWS EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: "us-east-1" 

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Clone the repository
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: ${{ secrets.AWS_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    # Step 3: Connect to EC2 via SSH and deploy the application
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          # Update packages and install Docker (if not already installed)
          sudo yum update -y
          sudo yum install -y docker
          sudo usermod -aG docker ec2-user
          sudo service docker start

          # Log in to Docker Hub and pull the latest image
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull adrylr/p7_scoring_app:latest

          # Stop and remove any existing containers using the same image
          docker ps -q --filter "ancestor=adrylr/p7_scoring_app:latest" | xargs -r docker stop
          docker ps -q --filter "ancestor=adrylr/p7_scoring_app:latest" | xargs -r docker rm

          # Run the Docker container
          docker run -d -p 80:8000 adrylr/p7_scoring_app:latest
